// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNkZTaRy2AwaZ1lUi9mNkbHcLK_GgK9po',
    appId: '1:364220532803:web:cbac82aebeb1eee136acf6',
    messagingSenderId: '364220532803',
    projectId: 'deepin-d0373',
    authDomain: 'deepin-d0373.firebaseapp.com',
    storageBucket: 'deepin-d0373.appspot.com',
    measurementId: 'G-VCSC21SKLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmnpJjSO6O8GzXlh0Wb_Wgt5J4PlV5PYM',
    appId: '1:364220532803:android:ae1e3c99635768fb36acf6',
    messagingSenderId: '364220532803',
    projectId: 'deepin-d0373',
    storageBucket: 'deepin-d0373.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyQT_eSdH6pkz83USn14jBQQCENS_jJQ4',
    appId: '1:364220532803:ios:89639363b028201236acf6',
    messagingSenderId: '364220532803',
    projectId: 'deepin-d0373',
    storageBucket: 'deepin-d0373.appspot.com',
    iosClientId: '364220532803-fffvcf64bt1qjcolunq1rqks2uhmepb4.apps.googleusercontent.com',
    iosBundleId: 'com.deepin.deepin',
  );
}
